version: "3.9"

services:
  # -------------------------------------
  # APPLICATION SERVICES
  # -------------------------------------
  chaos-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      LOG_LEVEL: INFO
      JSON_LOGS: "true"
      WEATHER_API_URL: http://weather-service:9000
      
      # Route traces to the local Alloy container
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_SERVICE_NAME: chaos-service
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
    depends_on:
      - weather-service
      - alloy
    deploy:
      resources:
        limits:
          memory: 256M

  weather-service:
    build:
      context: .
      dockerfile: Dockerfile.weather
    ports:
      - "9000:9000"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
      OTEL_SERVICE_NAME: weather-service
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_LOGS_EXPORTER: "none"
    depends_on:
      - alloy

  # -------------------------------------
  # OBSERVABILITY STACK
  # -------------------------------------
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100" # Expose to host so Host-Grafana can connect to localhost:3100
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200" # Expose to host so Host-Grafana can connect to localhost:3200
  mimir:
    image: grafana/mimir:latest
    command: ["-config.file=/etc/mimir.yaml"]
    ports:
      - "9009:9009"
    volumes:
      - ./mimir.yaml:/etc/mimir.yaml:ro
      - mimir-data:/data/mimir
  alloy:
    image: grafana/alloy:latest
    ports:
      - "4318:4318" # Expose to host so Host-Grafana can connect to localhost:12345
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      # Mount the Docker socket so Alloy can read the container logs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: [
      "run",
      "--server.http.listen-addr=0.0.0.0:12345",
      "/etc/alloy/config.alloy"
    ]
    depends_on:
      - loki
      - tempo

volumes:
  mimir-data: