{
 "title": "Application Observability: Golden Signals",
 "tags": [
  "python",
  "as-code",
  "lgtm",
  "production"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Critical Errors (Last 1h)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\".*chaos-app.*|.*weather-service.*\"} | json | level=\"error\" [1h]))"
    }
   ]
  },
  {
   "title": "HTTP Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(count_over_time({container=~\".*chaos-app.*|.*weather-service.*\"} | json | status_code >= 200 and status_code < 400 [$__auto])) / sum(count_over_time({container=~\".*chaos-app.*|.*weather-service.*\"} | json | status_code > 0 [$__auto]))) * 100"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({container=~\".*chaos-app.*|.*weather-service.*\"} | json | status_code > 0 [$__auto]))"
    }
   ]
  },
  {
   "title": "Application Log Volume & Severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({container=~\".*chaos-app.*|.*weather-service.*\"} | json [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Live Container Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "{container=~\".*chaos-app.*|.*weather-service.*\"} | json"
    }
   ]
  },
  {
   "title": "Slow Traces (>100ms)",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "{ .service.name = \"chaos-service\" || .service.name = \"weather-service\" } | duration > 100ms"
    }
   ]
  }
 ]
}